server:
  port: 8081


spring:
  redis:
    host: localhost
    port: 6379


  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db?options=-c%20TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  Kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.pit.employeems.event.EmployeeEvent
    bootstrap-servers: localhost:9092

