server:
  port: 8080

spring:

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: employee-service
          uri: http://employee-service:8081
          predicates:
            - Path=/employees,/employees/**

        - id: notification-service
          uri: http://notification-service:8082
          predicates:
            - Path=/notifications/**

        - id: audit-service
          uri: http://audit-service:8083
          predicates:
            - Path=/audits/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: TRACE